
version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11.4
      - image: cimg/postgres:14.9
        environment:
          POSTGRES_USER: ai_project_be
          POSTGRES_PASSWORD: ai_project_be
          POSTGRES_DB: ai_project_be
        ports:
          - 5432:5432
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
