# Generated by Django 4.2.4 on 2023-08-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('steps', models.TextField(max_length=2000)),
                ('description', models.TextField(max_length=2000)),
                ('features', models.TextField(max_length=2000)),
                ('interactions', models.TextField(max_length=2000)),
                ('colors', models.TextField(max_length=2000)),
                ('timeline', models.CharField(max_length=6)),
                ('saved', models.BooleanField(default=False)),
                ('tagline', models.TextField(max_length=2000)),
                ('collaborators', models.PositiveSmallIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
