# Generated by Django 4.2.4 on 2023-08-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
