# Generated by Django 4.2.4 on 2023-08-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timeline_int',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
