# Generated by Django 4.2.4 on 2023-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_timeline_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(default='python', max_length=2000),
            preserve_default=False,
        ),
    ]
