# Generated by Django 4.2.4 on 2023-09-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo_font',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='logo_url',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
