# Generated by Django 4.2.4 on 2023-09-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_logo_font_project_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo_font',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo_url',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
