# Generated by Django 4.2.4 on 2023-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
